"""Shared fixtures for v0.3.1 User UI acceptance tests.

Same infrastructure as v0.3.0 conftest; separate port (10063) so both
suites can run in parallel in CI without colliding.
"""

import subprocess
import sys
import time

import httpx
import pytest
from playwright.sync_api import sync_playwright

from sg_send_qa.utils.QA_Screenshot_Capture import ScreenshotCapture
from sg_send_qa.utils.QA_Transfer_Helper    import QA_Transfer_Helper
from sg_send_qa.utils.QA_UI_Server          import build_ui_serve_dir

try:
    from sgraph_ai_app_send.lambda__user.testing.Send__User_Lambda__Test_Server import (
        setup__send_user_lambda__test_server,
    )
except ImportError:
    setup__send_user_lambda__test_server = None


UI_PORT = 10063


# ---------------------------------------------------------------------------
# pytest markers
# ---------------------------------------------------------------------------

def pytest_configure(config):
    config.addinivalue_line("markers", "p0: P0 — deployment blocker")
    config.addinivalue_line("markers", "p1: P1 — requires human sign-off if failing")
    config.addinivalue_line("markers", "p2: P2 — bug filed, does not block")
    config.addinivalue_line("markers", "p3: P3 — nice to have")
    config.addinivalue_line("markers", "v031: v0.3.1 feature — requires v0.3.1 UI overlay")


# ---------------------------------------------------------------------------
# QA server (in-memory, session-scoped)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def send_server():
    """Start the real SG/Send User Lambda on a random port (in-memory storage)."""
    if setup__send_user_lambda__test_server is None:
        pytest.skip("sgraph_ai_app_send not installed — skipping v031 tests")
    with setup__send_user_lambda__test_server() as test_objs:
        yield test_objs


@pytest.fixture(scope="session")
def api_url(send_server):
    return send_server.server_url


# ---------------------------------------------------------------------------
# UI static server (session-scoped)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def ui_server(send_server, tmp_path_factory):
    """Serve the SG/Send v0.3.1 UI from the installed package on localhost:{UI_PORT}."""
    serve_dir = tmp_path_factory.mktemp("ui-server-v031")
    build_ui_serve_dir(
        api_url   = send_server.server_url,
        serve_dir = serve_dir,
        comment   = "Generated by v031 QA conftest",
    )

    proc = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(UI_PORT),
         "--directory", str(serve_dir), "--bind", "localhost"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    deadline = time.time() + 15
    while time.time() < deadline:
        try:
            r = httpx.get(f"http://localhost:{UI_PORT}/en-gb/", timeout=2)
            if r.status_code == 200:
                break
        except Exception:
            pass
        time.sleep(0.5)
    else:
        proc.kill()
        raise RuntimeError(f"v031 UI server failed to start on port {UI_PORT}")

    yield f"http://localhost:{UI_PORT}"

    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


@pytest.fixture(scope="session")
def ui_url(ui_server):
    return ui_server


# ---------------------------------------------------------------------------
# Playwright
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def playwright_instance():
    with sync_playwright() as p:
        yield p


@pytest.fixture(scope="session")
def browser(playwright_instance):
    browser = playwright_instance.chromium.launch(
        headless=True,
        args=["--font-render-hinting=none"],
    )
    yield browser
    browser.close()


@pytest.fixture(scope="session")
def browser_context(browser, ui_server):
    context = browser.new_context(
        viewport={"width": 1280, "height": 800},
        base_url=ui_server,
    )
    context.set_default_timeout(5_000)
    context.set_default_navigation_timeout(10_000)
    yield context
    context.close()


@pytest.fixture
def page(browser_context):
    page = browser_context.new_page()
    yield page
    page.close()


# ---------------------------------------------------------------------------
# Screenshots
# ---------------------------------------------------------------------------

@pytest.fixture
def screenshots(request):
    capture = ScreenshotCapture.from_request(request, test_target="qa_server")
    yield capture
    capture.save_metadata()


# ---------------------------------------------------------------------------
# TransferHelper
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def transfer_helper(send_server):
    return QA_Transfer_Helper(
        api_url      = send_server.server_url,
        access_token = send_server.access_token,
    )
