#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# qa__run-locally.sh — Serve the QA site v2 locally for development
#
# Serves sg_send_qa__site_v2/ on http://localhost:10064/
# No Ruby, no Jekyll, no build step — just Python's http.server.
#
# Screenshots load from the live site (https://qa.send.sgraph.ai) via full URLs
# embedded in the generated HTML pages — no local copy of screenshots needed.
#
# Usage:
#   ./scripts/qa__run-locally.sh
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

PORT=10064
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
SITE_DIR="$REPO_ROOT/sg_send_qa__site_v2"

if [ ! -d "$SITE_DIR" ]; then
    echo "ERROR: v2 site directory not found: $SITE_DIR"
    echo "Run this script from the repo root or scripts/ directory."
    exit 1
fi

# Inject build-info.js for local development
mkdir -p "$SITE_DIR/_common/js"
cat > "$SITE_DIR/_common/js/build-info.js" <<JSEOF
/* Generated by qa__run-locally.sh — local development only. Not committed. */
window.SGRAPH_BUILD = {
    appVersion: 'local-dev',
    uiVersion:  'qa-site-v2-local',
    buildTime:  '$(date -u +%Y-%m-%dT%H:%M:%SZ)',
    commit:     'local'
};
JSEOF

echo ""
echo "  QA Site v2 — local development"
echo "  ─────────────────────────────────────────────────────"
echo "  URL:          http://localhost:$PORT/"
echo "  Root:         $SITE_DIR"
echo "  Screenshots:  loading from https://qa.send.sgraph.ai"
echo "  ─────────────────────────────────────────────────────"
echo ""
echo "  Ctrl+C to stop"
echo ""

python3 -m http.server $PORT --directory "$SITE_DIR"
