"""UI static server builder for SG/Send QA.

Provides the single canonical _build_ui_serve_dir implementation,
extracted from tests/qa/v030/conftest.py and tests/standalone/conftest.py
(previously defined twice, nearly identical).

Assembles a flat static directory from the installed
sgraph_ai_app_send__ui__user package and injects build-info.js
pointing at the local QA server API — mirroring what
scripts/user__run-locally.sh does.

Usage:
    from sg_send_qa.utils.QA_UI_Server import build_ui_serve_dir
    build_ui_serve_dir(api_url="http://127.0.0.1:PORT", serve_dir=Path("/tmp/ui"))
"""

import re
import shutil
import datetime
from pathlib import Path

# CDN resources that must be replaced with local copies for offline testing
_CDN_PATCHES = {
    # sg-layout is loaded from tools.sgraph.ai CDN; substitute our bundled copy
    r'https://dev\.tools\.sgraph\.ai/core/sg-layout/[^"\']+sg-layout\.js':
        '/_vendor/sg-layout.js',
}

_STATIC_DIR = Path(__file__).parent.parent / "static"

UI_VERSION      = "v0.3.0"
UI_VERSION_BASE = "v0.3.0"   # base layer for IFD overlays


def _copy_ui_layer(pkg_root: Path, ui_version: str, serve_dir: Path) -> None:
    """Copy one UI version layer into serve_dir (dirs_exist_ok=True for overlays)."""
    ui_dir = pkg_root / "v0" / "v0.3" / ui_version
    if not ui_dir.exists():
        raise RuntimeError(f"UI directory not found: {ui_dir}")

    # _common — resolve symlinks so http.server can read them
    common_src = ui_dir / "_common"
    if common_src.exists():
        shutil.copytree(common_src, serve_dir / "_common",
                        symlinks=False, dirs_exist_ok=True)

    # Locale pages + route directories
    endb_src = ui_dir / "en-gb"
    if endb_src.exists():
        (serve_dir / "en-gb").mkdir(exist_ok=True)
        idx = endb_src / "index.html"
        if idx.exists():
            shutil.copy(idx, serve_dir / "en-gb" / "index.html")
        for route in ("download", "browse", "gallery", "v", "view", "welcome"):
            src = endb_src / route
            if src.is_dir():
                shutil.copytree(src, serve_dir / "en-gb" / route, dirs_exist_ok=True)

    # Test files (if present)
    test_files_src = ui_dir / "test-files"
    if test_files_src.exists():
        shutil.copytree(test_files_src, serve_dir / "test-files",
                        symlinks=False, dirs_exist_ok=True)

    # Patch CDN URLs in all HTML files (offline testing support)
    for html_file in serve_dir.rglob("*.html"):
        content = html_file.read_text(encoding="utf-8")
        patched = content
        for cdn_pattern, local_path in _CDN_PATCHES.items():
            patched = re.sub(cdn_pattern, local_path, patched)
        if patched != content:
            html_file.write_text(patched, encoding="utf-8")


def build_ui_serve_dir(api_url: str, serve_dir: Path,
                       ui_version: str = UI_VERSION,
                       comment: str = "Generated by QA server") -> None:
    """Assemble a flat static UI directory from the installed UI package.

    IFD (In-File-Delivery) overlay support: if ui_version is not the base
    version (v0.3.0), the base is copied first, then the overlay is applied
    on top. This mirrors what scripts/user__run-locally.sh does for v0.3.1+.

    Args:
        api_url:    Base URL of the QA server (e.g. http://127.0.0.1:54321).
        serve_dir:  Directory to populate. Created if it doesn't exist.
        ui_version: UI version to serve (default: v0.3.0). For overlays like
                    v0.3.1, the base (v0.3.0) is always applied first.
        comment:    Comment written into build-info.js (identifies caller).

    Raises:
        RuntimeError: If the UI package or version directory is not found.
        ImportError:  If sgraph_ai_app_send__ui__user is not installed.
    """
    import sgraph_ai_app_send__ui__user as _ui_pkg

    pkg_root  = Path(_ui_pkg.__file__).parent
    serve_dir = Path(serve_dir)
    serve_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: always copy the base version
    _copy_ui_layer(pkg_root, UI_VERSION_BASE, serve_dir)

    # Step 2: if this is an overlay version (IFD), apply it on top
    if ui_version != UI_VERSION_BASE:
        _copy_ui_layer(pkg_root, ui_version, serve_dir)

    # Serve local copies of CDN vendor files
    vendor_dir = serve_dir / "_vendor"
    vendor_dir.mkdir(exist_ok=True)
    # sg-layout.js and its module dependency sg-layout-events.js
    sg_layout_src = _STATIC_DIR / "sg-layout-v010.js"
    if sg_layout_src.exists():
        shutil.copy(sg_layout_src, vendor_dir / "sg-layout.js")
    sg_events_src = _STATIC_DIR / "sg-layout-events-v010.js"
    if sg_events_src.exists():
        shutil.copy(sg_events_src, vendor_dir / "sg-layout-events.js")

    # Root redirect
    (serve_dir / "index.html").write_text(
        '<!DOCTYPE html><html><head>'
        '<meta http-equiv="refresh" content="0;url=/en-gb/"></head>'
        '<body><a href="/en-gb/">Redirecting\u2026</a></body></html>'
    )

    # Inject build-info.js pointing at the QA server.
    # Note: v0.3.1+ index.html pages override uiVersion inline via JS,
    # so build-info.js reflects the base version — the page-level script
    # is the authoritative version signal for overlay pages.
    build_time = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    (serve_dir / "_common" / "js" / "build-info.js").write_text(
        f"/* {comment} */\n"
        f"window.SGRAPH_BUILD = {{\n"
        f"    appVersion : 'local-dev',\n"
        f"    uiVersion  : '{ui_version}',\n"
        f"    buildTime  : '{build_time}',\n"
        f"    apiEndpoint: '{api_url}'\n"
        f"}};\n"
    )
