"""UI static server builder for SG/Send QA.

Provides the single canonical _build_ui_serve_dir implementation,
extracted from tests/qa/v030/conftest.py and tests/standalone/conftest.py
(previously defined twice, nearly identical).

Assembles a flat static directory from the installed
sgraph_ai_app_send__ui__user package and injects build-info.js
pointing at the local QA server API — mirroring what
scripts/user__run-locally.sh does.

Usage:
    from sg_send_qa.utils.QA_UI_Server import build_ui_serve_dir
    build_ui_serve_dir(api_url="http://127.0.0.1:PORT", serve_dir=Path("/tmp/ui"))
"""

import shutil
import datetime
from pathlib import Path

UI_VERSION = "v0.3.0"


def build_ui_serve_dir(api_url: str, serve_dir: Path,
                       ui_version: str = UI_VERSION,
                       comment: str = "Generated by QA server") -> None:
    """Assemble a flat static UI directory from the installed UI package.

    Args:
        api_url:    Base URL of the QA server (e.g. http://127.0.0.1:54321).
        serve_dir:  Directory to populate. Created if it doesn't exist.
        ui_version: UI package version subdirectory (default: v0.3.0).
        comment:    Comment written into build-info.js (identifies caller).

    Raises:
        RuntimeError: If the UI package or version directory is not found.
        ImportError:  If sgraph_ai_app_send__ui__user is not installed.
    """
    import sgraph_ai_app_send__ui__user as _ui_pkg

    pkg_root = Path(_ui_pkg.__file__).parent
    ui_dir   = pkg_root / "v0" / "v0.3" / ui_version

    if not ui_dir.exists():
        raise RuntimeError(f"UI directory not found: {ui_dir}")

    serve_dir.mkdir(parents=True, exist_ok=True)

    # _common — resolve symlinks so http.server can read them
    shutil.copytree(ui_dir / "_common", serve_dir / "_common",
                    symlinks=False, dirs_exist_ok=True)

    # Locale pages + route directories
    (serve_dir / "en-gb").mkdir(exist_ok=True)
    shutil.copy(ui_dir / "en-gb" / "index.html",
                serve_dir / "en-gb" / "index.html")
    for route in ("download", "browse", "gallery", "v", "view", "welcome"):
        src = ui_dir / "en-gb" / route
        if src.is_dir():
            shutil.copytree(src, serve_dir / "en-gb" / route, dirs_exist_ok=True)

    # Test files (if present in package)
    test_files_src = ui_dir / "test-files"
    if test_files_src.exists():
        shutil.copytree(test_files_src, serve_dir / "test-files",
                        symlinks=False, dirs_exist_ok=True)

    # Root redirect
    (serve_dir / "index.html").write_text(
        '<!DOCTYPE html><html><head>'
        '<meta http-equiv="refresh" content="0;url=/en-gb/"></head>'
        '<body><a href="/en-gb/">Redirecting\u2026</a></body></html>'
    )

    # Inject build-info.js pointing at the QA server
    build_time = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    (serve_dir / "_common" / "js" / "build-info.js").write_text(
        f"/* {comment} */\n"
        f"window.SGRAPH_BUILD = {{\n"
        f"    appVersion : 'local-dev',\n"
        f"    uiVersion  : '{ui_version}',\n"
        f"    buildTime  : '{build_time}',\n"
        f"    apiEndpoint: '{api_url}'\n"
        f"}};\n"
    )
