"""Shared fixtures for v0.3.0 User UI acceptance tests.

Thin wrapper: all implementation lives in sg_send_qa/.
Starts a real in-memory SG/Send API server (QA server) and a UI static
server so Playwright tests run with no network, no S3, deterministically.
"""

import subprocess
import sys
import time

import httpx
import pytest
from playwright.sync_api import sync_playwright

from sg_send_qa.utils.QA_Screenshot_Capture import ScreenshotCapture
from sg_send_qa.utils.QA_Transfer_Helper    import QA_Transfer_Helper
from sg_send_qa.utils.QA_UI_Server          import build_ui_serve_dir

try:
    from sgraph_ai_app_send.lambda__user.testing.Send__User_Lambda__Test_Server import (
        setup__send_user_lambda__test_server,
    )
except ImportError:
    setup__send_user_lambda__test_server = None


UI_PORT = 10062


# ---------------------------------------------------------------------------
# pytest markers
# ---------------------------------------------------------------------------

def pytest_configure(config):
    config.addinivalue_line("markers", "p0: P0 — deployment blocker")
    config.addinivalue_line("markers", "p1: P1 — requires human sign-off if failing")
    config.addinivalue_line("markers", "p2: P2 — bug filed, does not block")
    config.addinivalue_line("markers", "p3: P3 — nice to have")


# ---------------------------------------------------------------------------
# QA server (in-memory, session-scoped)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def send_server():
    """Start the real SG/Send User Lambda on a random port (in-memory storage).

    Yields test_objs with:
        .server_url     — e.g. http://127.0.0.1:54321
        .access_token   — pre-generated random GUID
        .write_key      — pre-generated random GUID
    """
    if setup__send_user_lambda__test_server is None:
        pytest.skip("sgraph_ai_app_send not installed — skipping v030 tests")
    with setup__send_user_lambda__test_server() as test_objs:
        yield test_objs


@pytest.fixture(scope="session")
def api_url(send_server):
    """Base URL of the local QA server."""
    return send_server.server_url


# ---------------------------------------------------------------------------
# UI static server (session-scoped)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def ui_server(send_server, tmp_path_factory):
    """Serve the SG/Send UI from the installed package on localhost:{UI_PORT}.

    Calls build_ui_serve_dir from sg_send_qa.utils.QA_UI_Server — mirrors
    what scripts/user__run-locally.sh does but without a shell script.

    NOTE: Must bind to 'localhost' (not 127.0.0.1) — Web Crypto API requires
    a secure context; localhost qualifies, 127.0.0.1 does not in all browsers.
    """
    serve_dir = tmp_path_factory.mktemp("ui-server")
    build_ui_serve_dir(
        api_url   = send_server.server_url,
        serve_dir = serve_dir,
        comment   = "Generated by v030 QA conftest",
    )

    proc = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(UI_PORT),
         "--directory", str(serve_dir), "--bind", "localhost"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    deadline = time.time() + 15
    while time.time() < deadline:
        try:
            r = httpx.get(f"http://localhost:{UI_PORT}/en-gb/", timeout=2)
            if r.status_code == 200:
                break
        except Exception:
            pass
        time.sleep(0.5)
    else:
        proc.kill()
        raise RuntimeError(f"UI server failed to start on port {UI_PORT}")

    yield f"http://localhost:{UI_PORT}"

    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


@pytest.fixture(scope="session")
def ui_url(ui_server):
    """Base URL of the local UI server (alias for clarity)."""
    return ui_server


# ---------------------------------------------------------------------------
# Playwright browser + page
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def playwright_instance():
    with sync_playwright() as p:
        yield p


@pytest.fixture(scope="session")
def browser(playwright_instance):
    """Headless Chromium shared across the session."""
    browser = playwright_instance.chromium.launch(
        headless=True,
        args=["--font-render-hinting=none"],
    )
    yield browser
    browser.close()


@pytest.fixture(scope="session")
def browser_context(browser, ui_server):
    """Shared browser context with base_url set to the local UI.

    Default Playwright timeout is 30s — designed for slow production sites.
    Against a local in-memory server 5s is plenty, and makes failures fast
    rather than silently eating the CI budget.
    """
    context = browser.new_context(
        viewport={"width": 1280, "height": 800},
        base_url=ui_server,
    )
    context.set_default_timeout(5_000)
    context.set_default_navigation_timeout(10_000)
    yield context
    context.close()


@pytest.fixture
def page(browser_context):
    """Fresh page per test."""
    page = browser_context.new_page()
    yield page
    page.close()


# ---------------------------------------------------------------------------
# Screenshots
# ---------------------------------------------------------------------------

@pytest.fixture
def screenshots(request):
    """Screenshot capture fixture — saves PNGs + deduplicated metadata JSON.

    Groups screenshots by module (use case), not by individual method.
    Uses ScreenshotCapture from sg_send_qa.utils.QA_Screenshot_Capture.
    """
    capture = ScreenshotCapture.from_request(request, test_target="qa_server")
    yield capture
    capture.save_metadata()


# ---------------------------------------------------------------------------
# TransferHelper — create encrypted transfers via API (for download tests)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def transfer_helper(send_server):
    """QA_Transfer_Helper wired to the local QA server."""
    return QA_Transfer_Helper(
        api_url      = send_server.server_url,
        access_token = send_server.access_token,
    )
