"""Shared fixtures for v0.3.0 User UI acceptance tests.

Starts a real in-memory SG/Send API server and a UI static server
so Playwright tests run against a fully local stack — no network,
no S3, deterministic and fast.
"""

import pytest
import subprocess
import sys
import time
import os
import json
import base64
import httpx

from pathlib            import Path
from playwright.sync_api import sync_playwright

from sgraph_ai_app_send.lambda__user.testing.Send__User_Lambda__Test_Server import (
    setup__send_user_lambda__test_server,
)


UI_PORT = 10062


# ---------------------------------------------------------------------------
# pytest markers
# ---------------------------------------------------------------------------

def pytest_configure(config):
    config.addinivalue_line("markers", "p0: P0 — deployment blocker")
    config.addinivalue_line("markers", "p1: P1 — requires human sign-off if failing")
    config.addinivalue_line("markers", "p2: P2 — bug filed, does not block")
    config.addinivalue_line("markers", "p3: P3 — nice to have")


# ---------------------------------------------------------------------------
# API server (in-memory, session-scoped)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def send_server():
    """Start the real SG/Send User Lambda on a random port (in-memory storage).

    Yields test_objs with:
        .server_url     — e.g. http://127.0.0.1:54321
        .access_token   — pre-generated random GUID
        .write_key      — pre-generated random GUID
    """
    with setup__send_user_lambda__test_server() as test_objs:
        yield test_objs


@pytest.fixture(scope="session")
def api_url(send_server):
    """Base URL of the local API server."""
    return send_server.server_url


# ---------------------------------------------------------------------------
# UI static server (session-scoped)
# ---------------------------------------------------------------------------

UI_VERSION = "v0.3.0"


def _build_ui_serve_dir(api_url: str, serve_dir: Path) -> None:
    """Mirror what scripts/user__run-locally.sh does: assemble a flat static
    directory from the installed sgraph_ai_app_send__ui__user package and
    inject build-info.js pointing at the local API."""
    import sgraph_ai_app_send__ui__user as _ui_pkg
    import shutil
    import datetime

    pkg_root = Path(_ui_pkg.__file__).parent
    ui_dir   = pkg_root / "v0" / "v0.3" / UI_VERSION

    if not ui_dir.exists():
        raise RuntimeError(f"UI directory not found: {ui_dir}")

    serve_dir.mkdir(parents=True, exist_ok=True)

    # _common (resolving symlinks so http.server can read them)
    shutil.copytree(ui_dir / "_common", serve_dir / "_common",
                    symlinks=False, dirs_exist_ok=True)

    # Locale pages
    (serve_dir / "en-gb").mkdir(exist_ok=True)
    shutil.copy(ui_dir / "en-gb" / "index.html", serve_dir / "en-gb" / "index.html")
    for route in ("download", "browse", "gallery", "v", "view", "welcome"):
        src = ui_dir / "en-gb" / route
        if src.is_dir():
            shutil.copytree(src, serve_dir / "en-gb" / route, dirs_exist_ok=True)

    # Test files
    test_files_src = ui_dir / "test-files"
    if test_files_src.exists():
        shutil.copytree(test_files_src, serve_dir / "test-files",
                        symlinks=False, dirs_exist_ok=True)

    # Root redirect
    (serve_dir / "index.html").write_text(
        '<!DOCTYPE html><html><head>'
        '<meta http-equiv="refresh" content="0;url=/en-gb/"></head>'
        '<body><a href="/en-gb/">Redirecting…</a></body></html>'
    )

    # Inject build-info.js with API endpoint
    build_time = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    (serve_dir / "_common" / "js" / "build-info.js").write_text(
        f"/* Generated by QA conftest — local dev */\n"
        f"window.SGRAPH_BUILD = {{\n"
        f"    appVersion : 'local-dev',\n"
        f"    uiVersion  : '{UI_VERSION}',\n"
        f"    buildTime  : '{build_time}',\n"
        f"    apiEndpoint: '{api_url}'\n"
        f"}};\n"
    )


@pytest.fixture(scope="session")
def ui_server(send_server, tmp_path_factory):
    """Start the UI static server pointing at the local API.

    Builds a serve directory from the installed sgraph_ai_app_send__ui__user
    package (same layout as scripts/user__run-locally.sh) and serves it with
    python -m http.server on localhost:{UI_PORT}.

    NOTE: Must bind to 'localhost' (not 127.0.0.1) — Web Crypto API requires
    a secure context; localhost qualifies, 127.0.0.1 does not in all browsers.
    """
    serve_dir = tmp_path_factory.mktemp("ui-server")
    _build_ui_serve_dir(send_server.server_url, serve_dir)

    proc = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(UI_PORT),
         "--directory", str(serve_dir), "--bind", "localhost"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    deadline = time.time() + 15
    while time.time() < deadline:
        try:
            r = httpx.get(f"http://localhost:{UI_PORT}/en-gb/", timeout=2)
            if r.status_code == 200:
                break
        except Exception:
            pass
        time.sleep(0.5)
    else:
        proc.kill()
        raise RuntimeError(f"UI server failed to start on port {UI_PORT}")

    yield f"http://localhost:{UI_PORT}"

    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


@pytest.fixture(scope="session")
def ui_url(ui_server):
    """Base URL of the local UI server (alias for clarity)."""
    return ui_server


# ---------------------------------------------------------------------------
# Playwright browser + page
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def playwright_instance():
    with sync_playwright() as p:
        yield p


@pytest.fixture(scope="session")
def browser(playwright_instance):
    """Headless Chromium shared across the session."""
    browser = playwright_instance.chromium.launch(
        headless=True,
        args=["--font-render-hinting=none"],
    )
    yield browser
    browser.close()


@pytest.fixture(scope="session")
def browser_context(browser, ui_server):
    """Shared browser context with base_url set to the local UI."""
    context = browser.new_context(
        viewport={"width": 1280, "height": 800},
        base_url=ui_server,
    )
    yield context
    context.close()


@pytest.fixture
def page(browser_context):
    """Fresh page per test."""
    page = browser_context.new_page()
    yield page
    page.close()


# ---------------------------------------------------------------------------
# Screenshots (reuses the project convention)
# ---------------------------------------------------------------------------

def _cdp_screenshot(page, path):
    """Take screenshot via CDP, bypassing Playwright's font-wait logic."""
    cdp    = page.context.new_cdp_session(page)
    result = cdp.send("Page.captureScreenshot", {"format": "png"})
    cdp.detach()
    Path(path).write_bytes(base64.b64decode(result["data"]))


@pytest.fixture
def screenshots(request):
    """Screenshot capture fixture — saves PNGs + metadata JSON."""
    test_name = request.node.name.replace("test_", "")
    shots_dir = Path("sg_send_qa__site/pages/use-cases") / test_name / "screenshots"
    shots_dir.mkdir(parents=True, exist_ok=True)

    captured = []

    class ScreenshotCapture:
        def capture(self, page, name, description=""):
            path = shots_dir / f"{name}.png"
            _cdp_screenshot(page, str(path))
            captured.append({"name": name, "path": str(path), "description": description})

        @property
        def all(self):
            return captured

        def save_metadata(self):
            meta = {
                "test_name"  : test_name,
                "test_doc"   : request.node.obj.__doc__ or "",
                "screenshots": captured,
            }
            (shots_dir / "_metadata.json").write_text(json.dumps(meta, indent=2))

    capture = ScreenshotCapture()
    yield capture
    capture.save_metadata()


# ---------------------------------------------------------------------------
# TransferHelper — create encrypted transfers via API (for download tests)
# ---------------------------------------------------------------------------

class TransferHelper:
    """Create real encrypted transfers via the API without a browser.

    Matches the browser's Web Crypto encryption exactly:
      - AES-256-GCM, 12-byte random IV prepended to ciphertext
      - SGMETA envelope: magic(7) + length(4) + JSON metadata + content
    """

    SGMETA_MAGIC = bytes([0x53, 0x47, 0x4D, 0x45, 0x54, 0x41, 0x00])  # "SGMETA\0"

    def __init__(self, api_url, access_token=None):
        self.api_url = api_url
        self.headers = {}
        if access_token:
            self.headers["x-sgraph-access-token"] = access_token

    def create_and_complete(self, payload: bytes, content_type="application/octet-stream"):
        """Create → upload → complete a transfer.  Returns transfer_id."""
        create_resp = httpx.post(
            f"{self.api_url}/api/transfers/create",
            json={"file_size_bytes": len(payload), "content_type_hint": content_type},
            headers=self.headers,
        )
        create_resp.raise_for_status()
        tid = create_resp.json()["transfer_id"]

        httpx.post(
            f"{self.api_url}/api/transfers/upload/{tid}",
            content=payload,
            headers={**self.headers, "content-type": "application/octet-stream"},
        ).raise_for_status()

        httpx.post(
            f"{self.api_url}/api/transfers/complete/{tid}",
            headers=self.headers,
        ).raise_for_status()

        return tid

    def upload_encrypted(self, plaintext: bytes, filename="test.txt"):
        """Encrypt client-side (matching browser Web Crypto), upload, return (transfer_id, base64url_key)."""
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        key_bytes = os.urandom(32)
        iv        = os.urandom(12)
        aesgcm    = AESGCM(key_bytes)

        # Build SGMETA envelope
        meta_json = json.dumps({"filename": filename}).encode()
        meta_len  = len(meta_json).to_bytes(4, "big")
        envelope  = self.SGMETA_MAGIC + meta_len + meta_json + plaintext

        # Encrypt: IV prepended to ciphertext (matches browser format)
        ciphertext = iv + aesgcm.encrypt(iv, envelope, None)

        tid = self.create_and_complete(ciphertext)

        # base64url key (no padding) — matches SendCrypto.exportKey
        key_b64 = base64.urlsafe_b64encode(key_bytes).rstrip(b"=").decode()
        return tid, key_b64


@pytest.fixture(scope="session")
def transfer_helper(send_server):
    """TransferHelper wired to the local API server."""
    return TransferHelper(send_server.server_url, send_server.access_token)
