"""Self-contained fixtures for standalone browser tests.

Starts a real in-memory SG/Send API server and a UI static server
so Playwright tests run against a fully local stack — no network,
no S3, deterministic and fast.

This conftest is intentionally independent of tests/qa/v030/conftest.py
so it can serve as a reference implementation and be debugged in isolation.

Setup requirements (Claude Code session):
    python3.12 -m venv /tmp/venv312
    source /tmp/venv312/bin/activate
    pip install -r requirements.txt
    python -m playwright install --with-deps chromium
    git clone --depth 1 -b dev https://github.com/the-cyber-boardroom/SGraph-AI__App__Send /tmp/sgraph-send-ref
    pip install -e /tmp/sgraph-send-ref --no-deps
    pip install osbot-fast-api osbot-fast-api-serverless fastapi-mcp mgraph-ai-service-cache mgraph-ai-service-cache-client issues-fs-cli
"""

import pytest
import subprocess
import sys
import time
import os
import json
import base64
import httpx

from pathlib             import Path
from playwright.sync_api import sync_playwright

try:
    from sgraph_ai_app_send.lambda__user.testing.Send__User_Lambda__Test_Server import (
        setup__send_user_lambda__test_server,
    )
except ImportError:
    setup__send_user_lambda__test_server = None


UI_PORT     = 10063                # different from v030 to avoid conflicts
UI_VERSION  = "v0.3.0"
SCREENSHOTS = Path("sg_send_qa__site/pages/use-cases/access_gate/screenshots")


# ---------------------------------------------------------------------------
# API server
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def send_server():
    """Start the real SG/Send User Lambda on a random port (in-memory)."""
    if setup__send_user_lambda__test_server is None:
        pytest.skip("sgraph_ai_app_send not installed — see docstring for setup")
    with setup__send_user_lambda__test_server() as test_objs:
        yield test_objs


# ---------------------------------------------------------------------------
# UI static server
# ---------------------------------------------------------------------------

def _build_ui_serve_dir(api_url: str, serve_dir: Path) -> None:
    """Build a static UI directory from the installed package."""
    import sgraph_ai_app_send__ui__user as _ui_pkg
    import shutil
    import datetime

    pkg_root = Path(_ui_pkg.__file__).parent
    ui_dir   = pkg_root / "v0" / "v0.3" / UI_VERSION

    if not ui_dir.exists():
        raise RuntimeError(f"UI directory not found: {ui_dir}")

    serve_dir.mkdir(parents=True, exist_ok=True)

    # _common (resolving symlinks so http.server can read them)
    shutil.copytree(ui_dir / "_common", serve_dir / "_common",
                    symlinks=False, dirs_exist_ok=True)

    # Locale pages
    (serve_dir / "en-gb").mkdir(exist_ok=True)
    shutil.copy(ui_dir / "en-gb" / "index.html", serve_dir / "en-gb" / "index.html")
    for route in ("download", "browse", "gallery", "v", "view", "welcome"):
        src = ui_dir / "en-gb" / route
        if src.is_dir():
            shutil.copytree(src, serve_dir / "en-gb" / route, dirs_exist_ok=True)

    # Test files
    test_files_src = ui_dir / "test-files"
    if test_files_src.exists():
        shutil.copytree(test_files_src, serve_dir / "test-files",
                        symlinks=False, dirs_exist_ok=True)

    # Root redirect
    (serve_dir / "index.html").write_text(
        '<!DOCTYPE html><html><head>'
        '<meta http-equiv="refresh" content="0;url=/en-gb/"></head>'
        '<body><a href="/en-gb/">Redirecting…</a></body></html>'
    )

    # Inject build-info.js with API endpoint
    build_time = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    (serve_dir / "_common" / "js" / "build-info.js").write_text(
        f"/* Generated by standalone conftest */\n"
        f"window.SGRAPH_BUILD = {{\n"
        f"    appVersion : 'local-dev',\n"
        f"    uiVersion  : '{UI_VERSION}',\n"
        f"    buildTime  : '{build_time}',\n"
        f"    apiEndpoint: '{api_url}'\n"
        f"}};\n"
    )


@pytest.fixture(scope="session")
def ui_server(send_server, tmp_path_factory):
    """Serve the UI from the installed package on localhost:{UI_PORT}."""
    serve_dir = tmp_path_factory.mktemp("ui-server")
    _build_ui_serve_dir(send_server.server_url, serve_dir)

    proc = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(UI_PORT),
         "--directory", str(serve_dir), "--bind", "localhost"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    deadline = time.time() + 15
    while time.time() < deadline:
        try:
            r = httpx.get(f"http://localhost:{UI_PORT}/en-gb/", timeout=2)
            if r.status_code == 200:
                break
        except Exception:
            pass
        time.sleep(0.5)
    else:
        proc.kill()
        raise RuntimeError(f"UI server failed to start on port {UI_PORT}")

    yield f"http://localhost:{UI_PORT}"

    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


@pytest.fixture(scope="session")
def ui_url(ui_server):
    """Base URL of the local UI server."""
    return ui_server


# ---------------------------------------------------------------------------
# Playwright browser + page
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def playwright_instance():
    with sync_playwright() as p:
        yield p


@pytest.fixture(scope="session")
def browser(playwright_instance):
    """Headless Chromium shared across the session."""
    browser = playwright_instance.chromium.launch(
        headless=True,
        args=["--font-render-hinting=none"],
    )
    yield browser
    browser.close()


@pytest.fixture(scope="session")
def browser_context(browser, ui_server):
    """Shared browser context with base_url set to the local UI."""
    context = browser.new_context(
        viewport={"width": 1280, "height": 800},
        base_url=ui_server,
    )
    yield context
    context.close()


@pytest.fixture
def page(browser_context):
    """Fresh page per test."""
    page = browser_context.new_page()
    yield page
    page.close()


# ---------------------------------------------------------------------------
# Screenshots
# ---------------------------------------------------------------------------

def _cdp_screenshot(page, path):
    """Take screenshot via CDP, bypassing Playwright's font-wait logic."""
    cdp    = page.context.new_cdp_session(page)
    result = cdp.send("Page.captureScreenshot", {"format": "png"})
    cdp.detach()
    Path(path).write_bytes(base64.b64decode(result["data"]))


@pytest.fixture
def screenshots(request):
    """Capture screenshots to the access_gate screenshots directory.

    Saves PNGs + _metadata.json that the CI auto-commit workflow picks up.
    """
    method_name = request.node.name
    SCREENSHOTS.mkdir(parents=True, exist_ok=True)

    captured = []

    class ScreenshotCapture:
        def capture(self, page, name, description=""):
            path = SCREENSHOTS / f"{name}.png"
            _cdp_screenshot(page, str(path))
            captured.append({"name": name, "path": str(path), "description": description})

        @property
        def all(self):
            return captured

    capture = ScreenshotCapture()
    yield capture

    # Append metadata
    meta_path = SCREENSHOTS / "_metadata.json"
    if meta_path.exists():
        existing = json.loads(meta_path.read_text())
    else:
        existing = {
            "use_case"   : "access_gate",
            "module"     : "test__access_gate_standalone",
            "tests"      : [],
            "screenshots": [],
        }

    existing["tests"].append({
        "method"      : method_name,
        "doc"         : request.node.obj.__doc__ or "",
        "screenshots" : [s["name"] for s in captured],
    })
    existing["screenshots"].extend(captured)
    meta_path.write_text(json.dumps(existing, indent=2))
